### ISSUE TITLE
accept a folder with calendars instead of  listing .ics files

### ISSUE THREAD

**Issue by teto** [b1rger/carl#149]
hi,

this is amazing. I try to use https://github.com/geier/khal/ but there is a bunch of nasty bugs and I prefer rust applications. 
I use vdirsyncer to synchronize my calendars across machines so I end up with folders with .ics files.

Reading the readme, I need to set the .ics files ( https://github.com/b1rger/carl/blob/main/data/config.toml)  manually but I cant imagine how this works as a workflow ? as time passes my ics gets obsolete so I should remove it and add a new one ? 
or was this imagined to work only with recurrent events in .ics files ?

**Comment by b1rger** [comment]
Hi, glad you like `carl`!

I'm not sure if I understand your question, but you should be able to set `file = ` to point to a directory. `carl` then tries to read events from every file in the directory.

**Comment by teto** [comment]
Indeed it worked ! I might add this package to https://github.com/NixOS/nixpkgs/ .

Maybe add an example with folder in the example config.toml ? Great job !
